=== Koha-Community/Koha/koha-tmpl/intranet-tmpl/prog/en/data/marc21_field_CF.xsd
<?xml version="1.0"?>
<xs:schema xmlns="http://koha-community.org" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://koha-community.org" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.1">
  <xs:annotation>
    <xs:documentation>Control field plugin type of materials schema</xs:documentation>
  </xs:annotation>


  <xs:element name="Tagfield" type="TagfieldType" nillable="false">
    <xs:annotation>
      <xs:documentation>Element indicating the control field</xs:documentation>
    </xs:annotation>
  </xs:element>


  <xs:complexType name="TagfieldType">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element name="Material" type="MaterialType"/>
    </xs:sequence>
    <xs:attribute name="tag" type="controltagDataType" use="required"/>
  </xs:complexType>


  <xs:simpleType name="controltagDataType">
    <xs:restriction base="xs:string">
      <xs:whiteSpace value="collapse"/>
      <xs:pattern value="00[1-9A-Za-z]{1}"/>
    </xs:restriction>
  </xs:simpleType>


  <xs:complexType name="MaterialType">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element name="name" type="xs:string"/>
      <xs:element name="description" type="xs:string"/>
      <xs:element name="Position" type="PositionType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="id" type="idDataType" use="required"/>
  </xs:complexType>


  <xs:simpleType name="idDataType">
    <xs:restriction base="xs:string">
      <xs:whiteSpace value="collapse"/>
      <xs:enumeration value="BKS"/>
      <xs:enumeration value="CF"/>
      <xs:enumeration value="MP"/>
      <xs:enumeration value="MU"/>
      <xs:enumeration value="CR"/>
      <xs:enumeration value="VM"/>
      <xs:enumeration value="MX"/>
    </xs:restriction>
  </xs:simpleType>


  <xs:complexType name="PositionType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="urltext" type="xs:string" minOccurs="0"/>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="description" type="xs:string"/>
      <xs:element name="Value" type="ValueType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="url" type="xs:anyURI"/>
    <xs:attribute name="pos" type="posDataType" use="required"/>
  </xs:complexType>


  <xs:simpleType name="posDataType">
    <xs:restriction base="xs:string">
      <xs:whiteSpace value="collapse"/>
      <xs:pattern value="[0-9]+(-[0-9]+)?"/>
    </xs:restriction>
  </xs:simpleType>


  <xs:complexType name="ValueType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="description" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="code" type="xs:string" use="required"/>
  </xs:complexType>


</xs:schema>

=== Koha-Community/Koha/koha-tmpl/intranet-tmpl/prog/en/data/marc21_field_007.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE stylesheet>

<Tagfield tag="007" xmlns="http://koha-community.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="./marc21_field_CF.xsd">
  <Material id="MPS"><name>Maps</name><description></description>
    <Position pos="00"><name>Category of material</name><description></description>
      <Value code="a"><description>Map</description></Value>
    </Position>
    <Position pos="01"><name>Specific material designation</name><description>Special class of cartographic material to which the item belongs. Usually the class of physical object, e.g., a diagram.</description>
      <Value code="d"><description>Atlas</description></Value>
      <Value code="g"><description>Diagram</description></Value>
      <Value code="j"><description>Map</description></Value>
      <Value code="k"><description>Profile</description></Value>
      <Value code="q"><description>Model</description></Value>
      <Value code="r"><description>Remote-sensing image</description></Value>
      <Value code="s"><description>Section</description></Value>
      <Value code="u"><description>Unspecified</description></Value>
      <Value code="y"><description>View</description></Value>
      <Value code="z"><description>Other</description></Value>
      <Value code="|"><description>No attempt to code</description></Value>
    </Position>
    <Position pos="02"><name>Undefined</name><description>Contains a blank (#) or a fill character (|).</description>
    </Position>
    <Position pos="03"><name>Color</name><description>Whether the item is in one color or multicolored</description>
      <Value code="a"><description>One color</description></Value>
      <Value code="c"><description>Multicolored</description></Value>
      <Value code="|"><description>No attempt to code</description></Value>
    </Position>
    <Position pos="04"><name>Physcial Description</name><description>Material out of which the cartographic item is made.</description>
      <Value code="a"><description>Paper</description></Value>
      <Value code="b"><description>Wood</description></Value>
      <Value code="c"><description>Stone</description></Value>
      <Value code="d"><description>Metal</description></Value>
      <Value code="e"><description>Synthetic</description></Value>
      <Value code="f"><description>Skin</description></Value>
      <Value code="g"><description>Textiles</description></Value>
      <Value code="i"><description>Plastic</description></Value>
      <Value code="j"><description>Glass</description></Value>
      <Value code="l"><description>Vinyl</description></Value>
      <Value code="n"><description>Vellum</description></Value>
      <Value code="p"><description>Plaster</description></Value>
      <Value code="q"><description>Flexible base photographic, positive</description></Value>
      <Value code="r"><description>Flexible base photographic, negative</description></Value>
      <Value code="s"><description>Non-flexible base photographic, positive</description></Value>
      <Value code="t"><description>Non-flexible base photographic, negative</description></Value>
      <Value code="u"><description>Unknown</description></Value>
      <Value code="v"><description>Leather</description></Value>
      <Value code="w"><description>Parchment</description></Value>
      <Value code="x"><description>Not applicable</description></Value>
      <Value code="y"><description>Other photographic medium</description></Value>
      <Value code="z"><description>Other</description></Value>
      <Value code="|"><description>No attempt to code</description></Value>
    </Position>
    <Position pos="05"><name>Type of reproduction</name><description>Whether the cartographic item is a facsimile or other type of reproduction.</description>
      <Value code="f"><description>Facsimile</description></Value>
      <Value code="n"><description>Not applicable</description></Value>
      <Value code="u"><description>Unknown</description></Value>
      <Value code="z"><description>Other</description></Value>
      <Value code="|"><description>No attempt to code</description></Value>
    </Position>
    <Position pos="06"><name>Production/reproduction details</name><description>Photographic technique used to produce the cartographic item.</description>
      <Value code="a"><description>Photocopy, blueline print</description></Value>
      <Value code="b"><description>Photocopy</description></Value>
      <Value code="c"><description>Pre-production</description></Value>
      <Value code="d"><description>Film</description></Value>
      <Value code="u"><description>Unknown</description></Value>
      <Value code="z"><description>Other</description></Value>
      <Value code="|"><description>No attempt to code</description></Value>
    </Position>
    <Position pos="07"><name>Positive/negative aspect</name><description>Positive/negative aspect of the photocopy or film of the cartographic item, also referred to as polarity.</description>
      <Value code="a"><description>Positive</description></Value>
      <Value code="b"><description>Negative</description></Value>
      <Value code="m"><description>Mixed polarity</description></Value>
      <Value code="n"><description>Not applicable</description></Value>
      <Value code="|"><description>No attempt to code</description></Value>
    </Position>
  </Material>
  <Material id="ER"><name>Electronic resources</name><description></description>
    <Position pos="00"><name>Category of material</name><description>One-character alphabetic code that indicates the category of material to which the item belongs is electronic resource (e.g, programs, data files, image files, digitized audio and video tapes, etc.).</description>
      <Value code="c"><description>Electronic resource</description></Value>
    </Position>
    <Position pos="01"><name>Specific material designation</name><description>Special class of material (usually the class of physical object) to which an item belongs (e.g., a magnetic disk).</description>
      <Value code="a"><description>Tape cartridge</description></Value>
      <Value code="b"><description>Chip cartridge</description></Value>
      <Value code="c"><description>Computer optical disc cartridge</description></Value>
      <Value code="d"><description>Computer disc, type unspecified</description></Value>
      <Value code="e"><description>Computer disc cartridge</description></Value>
      <Value code="f"><description>Tape cassette</description></Value>
      <Value code="h"><description>Tape reel</description></Value>
      <Value code="j"><description>Magnetic disk</description></Value>
      <Value code="k"><description>Computer card</description></Value>
      <Value code="m"><description>Magneto-optical disc</description></Value>
      <Value code="o"><description>Optical disc</description></Value>
      <Value code="r"><description>Remote</description></Value>
      <Value code="s"><description>Standalone device</description></Value>
      <Value code="u"><description>Unspecified</description></Value>
      <Value code="z"><description>Other</description></Value>
      <Value code="|"><description>No attempt to code</description></Value>
    </Position>
    <Position pos="02"><name>Undefined</name><description>Contains a blank (#) or a fill character (|).</description>
    </Position>
    <Position pos="03"><name>Color</name><description>Whether the item is one color or multicolored.</description>
      <Value code="a"><description>One color</description></Value>
      <Value code="b"><description>Black-and-white</description></Value>
      <Value code="c"><description>Multicolored</description></Value>
      <Value code="g"><description>Gray scale</description></Value>
      <Value code="m"><description>Mixed</description></Value>
      <Value code="n"><description>Not applicable</description></Value>
      <Value code="u"><description>Unknown</description></Value>
      <Value code="z"><description>Other</description></Value>
      <Value code="|"><description>No attempt to code</description></Value>
    </Position>
    <Position pos="04"><name>Dimensions</name><description>Dimensions of the medium used to encode the electronic resource. Only the most common dimensions are indicated. In many cases the dimensions apply to the container in which a magnetic or optical medium is encased. The field 007/04 code corresponding to the dimensions given in the description of the item are used. If no code exactly matches the dimensions of the medium (or container), code z is used.
    </description>
      <Value code="a"><description>3 1/2 in.</description></Value>
      <Value code="e"><description>12 in.</description></Value>
      <Value code="g"><description>4 3/4 in. or 12 cm.</description></Value>
      <Value code="i"><description>1 1/8 x 2 3/8 in.</description></Value>
      <Value code="j"><description>3 7/8 x 2 1/2 in.</description></Value>
      <Value code="n"><description>Not applicable</description></Value>
      <Value code="o"><description>5 1/4 in.</description></Value>
      <Value code="u"><description>Unknown</description></Value>
      <Value code="v"><description>8 in.</description></Value>
      <Value code="z"><description>Other</description></Value>
      <Value code="|"><description>No attempt to code</description></Value>
    </Position>
    <Position pos="05"><name>Sound</name><description>Whether the production of sound is an integral part of an electronic resource.</description>
      <Value code="#"><description>No sound (silent)</description></Value>
      <Value code="a"><description>Sound</description></Value>
      <Value code="u"><description>Unknown</description></Value>
      <Value code="|"><description>No attempt to code</description></Value>
    </Position>
